### ISSUE TITLE
Wondering if you have a subscript features

### ISSUE THREAD

**Issue by julclu** [PfisterFactor/bear-equation-render#2]
Export to bear button not working? Perhaps I'm not looking at the right thing... Also, do you have subscript support? I know this is an old little project but would be really useful for me!

**Comment by PfisterFactor** [comment]
Sometimes it's buggy and takes a bit but as long as you have the right note identifier in the box it should work when you press the button. And what do you mean by subscript support, if you type "x_1" it'll write an x with a subscript of 1. The equation render follows the ASCII math format. http://asciimath.org/

Granted I don't know if the repository is updated with my local branch so I'll look into it sometime this week

**Comment by julclu** [comment]
Ah - just couldn't find that resource through my preliminary google - thanks! And it did seem to just take a while and was a bit buggy, but ended up working. Appreciate the help!
